
/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.*/
import java.util.*;

public class Find_Difference {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter the string1: ");
        String str1 = sc.nextLine();
        System.out.print("Enter the string2: ");
        String str2 = sc.nextLine();
        System.out.println(difference(str1, str2));
    }

    public static char difference(String s, String t) {
        int diff = 0;
        for (int i = 0; i < s.length(); i++) {
            diff -= s.charAt(i);
            diff += t.charAt(i);
        }
        diff += t.charAt(s.length());
        return (char) diff;
    }
}